version: "3.7"
services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        command: "docker:watch"
        env_file: .env
        ports:
            - "4000:8080"
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/app
    postgres:
        image: postgres
        env_file: .env
        ports:
            - "$PGSQL_DATABASE_EXPOSED_PORT:5432"
        environment:
            - POSTGRES_DB=godfather
            - "POSTGRES_USER=$PGSQL_DATABASE_USER"
            - "POSTGRES_PASSWORD=$PGSQL_DATABASE_PASSWORD"
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
        external: true
