name: Build and push Docker image.

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The name of the tag.'
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Release build
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          file: ./Dockerfile.prod
          push: true
          tags: soumil07/godfather:${{ github.event.release.tag_name }}
      - name: Push Alpha build
        id: docker_build_alpha
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          file: ./Dockerfile.prod
          push: true
          tags: soumil07/godfather:${{ github.event.inputs.tag_name }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest || steps.docker_build_alpha.outputs.digest }}
      - name: Discord Webhook (Alpha)
        run: "curl -i --fail \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{\"embeds\": [{\"color\": 899053, \"author\": {\"icon_url\": \"https://www.docker.com/sites/default/files/d8/styles/role_icon/public/2019-07/Docker-Logo-White-RGB_Moby.png?itok=VwIPWvAs\", \"name\": \"Docker Hub\"}, \"description\": \"Image pushed to [soumil07/godfather:${{ github.event.inputs.tag_name }}](https://hub.docker.com/r/soumil07/godfather) by soumil07.\", \"fields\": [{ \"name\": \"Image Digest(s)\", \"value\": \"${{steps.docker_build_alpha.outputs.digest}}\"}] }]}'
          \"${{ secrets.DISCORD_WEBHOOK }}\""
        if: ${{ github.event_name == 'workflow_dispatch' }}
      - name: Discord Webhook (Production)
        run: "curl -i --fail \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{\"embeds\": [{\"color\": 899053, \"author\": {\"icon_url\": \"https://www.docker.com/sites/default/files/d8/styles/role_icon/public/2019-07/Docker-Logo-White-RGB_Moby.png?itok=VwIPWvAs\", \"name\": \"Docker Hub\"}, \"description\": \"Image pushed to [soumil07/godfather:${{ github.event.release.tag_name }}](https://hub.docker.com/r/soumil07/godfather) by soumil07.\", \"fields\": [{ \"name\": \"Image Digest(s)\", \"value\": \"${{steps.docker_build.outputs.digest}}\"}] }]}'
          \"${{ secrets.DISCORD_WEBHOOK }}\""
        if: ${{ github.event_name == 'release' }}
