name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create src/config.ts
        run: |
          pushd src &&
          cp config.example.ts config.ts &&
          popd
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          file: ./Dockerfile.prod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: soumil07/godfather:${GITHUB_REF##*/}
          tag_with_ref: true
